FROM registry-cdn.hpg.nz/quay/fedora/fedora:44@sha256:a5b040132e11505954afec29098bd1838d5a7c4c0885c8e5943e1d4fb5a633f8

# Toolbox container
RUN yum -y install wireguard-tools avahi avahi-tools && \
    yum clean all