FROM registry.access.redhat.com/ubi10/ubi-minimal:10.2-1784669047@sha256:04140c8d78c6c6915b5c1fdad2f16d10eac3630c3339999ccdf659d8c903be50

USER root

RUN microdnf -y install \
    php \
    php-fpm \
    php-cli \
    php-opcache \
    php-mysqlnd \
    php-gd \
    php-intl \
    php-mbstring \
    php-xml \
    php-json \
    php-curl \
    php-zip \
    php-bcmath \
    php-soap \
    php-process \
    php-pecl-redis \
    php-pdo \
    php-pgsql \
    php-imagick \
    shadow-utils \
 && microdnf clean all

RUN sed -ri \
    -e 's!^listen = .*!listen = 0.0.0.0:9000!' \
    -e 's!^;?clear_env = .*!clear_env = no!' \
    /etc/php-fpm.d/www.conf

# Make logs container-friendly
RUN sed -ri \
    -e 's!^error_log = .*!error_log = /proc/self/fd/2!' \
    /etc/php-fpm.conf \
    && sed -ri \
    -e 's!^;?catch_workers_output = .*!catch_workers_output = yes!' \
    -e 's!^;?access.log = .*!access.log = /proc/self/fd/2!' \
    /etc/php-fpm.d/www.conf

RUN mkdir -p /run/php-fpm \
 && chown -R 0:0 /run/php-fpm \
 && chmod -R g+rwX /run/php-fpm

EXPOSE 9000

CMD ["/usr/sbin/php-fpm", "-F"]