FROM registry.access.redhat.com/ubi10/ubi-minimal:10.2-1779862102@sha256:7dc60d7777e010c50f5e041ff069112b379c3d5eef2823d20871c67cf663f10c

USER root

RUN microdnf -y install \
    php \
    php-fpm \
    php-cli \
    php-opcache \
    php-mysqlnd \
    php-gd \
    php-intl \
    php-mbstring \
    php-xml \
    php-json \
    php-curl \
    php-zip \
    php-bcmath \
    php-soap \
    php-process \
    php-pecl-redis \
    php-pdo \
    php-pgsql \
    shadow-utils \
 && microdnf clean all

RUN sed -ri \
    -e 's!^listen = .*!listen = 0.0.0.0:9000!' \
    -e 's!^;?clear_env = .*!clear_env = no!' \
    /etc/php-fpm.d/www.conf

# Make logs container-friendly
RUN sed -ri \
    -e 's!^error_log = .*!error_log = /proc/self/fd/2!' \
    /etc/php-fpm.conf \
    && sed -ri \
    -e 's!^;?catch_workers_output = .*!catch_workers_output = yes!' \
    -e 's!^;?access.log = .*!access.log = /proc/self/fd/2!' \
    /etc/php-fpm.d/www.conf

EXPOSE 9000

CMD ["/usr/sbin/php-fpm", "-F"]