FROM quay.io/fedora/fedora:44@sha256:7fdb46dc6707bab9495ee0079b4d769c32ac926e4484bbc843db21d262f4db25

LABEL org.opencontainers.image.source=https://github.com/hrrrsn/containers
LABEL org.opencontainers.image.description="Fedora image with Nginx and PHP"

COPY nginx.conf /etc/nginx/nginx.conf
COPY entry.sh /entry.sh
COPY php.ini-development /etc/php.ini

RUN dnf upgrade -y && \
    dnf install -y \
    rsync \
    nginx \
    procps \
    gettext \
    curl \
    php-fpm \
    php-cli \
    php-gd \
    php-intl \
    php-mysqlnd \
    php-pdo \
    php-pgsql \
    php-xml \
    php-opcache \
    php-mbstring \
    php-zip \
    php-curl && \
    dnf clean all && \
    rm -rf /var/cache/dnf && \
    mkdir -p /run/php-fpm/ && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log && \
    ln -sf /dev/stderr /var/log/php-fpm/error.log && \
    ln -sf /dev/stderr /var/log/php-fpm/www-error.log && \
    chmod +x /entry.sh && \
    for dir in /etc/nginx /usr/share/nginx /run /entry.sh; do \
        chgrp -R 0 $dir && chmod -R g=u $dir; \
    done && \
    echo "<?php phpinfo(); ?>" > /usr/share/nginx/html/phpinfo.php

EXPOSE 8080

CMD ["/entry.sh"]
