FROM tautulli/tautulli:v2.18.0@sha256:f8b4a2693198b67497ecf4a35367eb7b40e91a7b225551b61587df164f6a99b1

RUN for dir in /config /app; do \
        chgrp -R 0 $dir && chmod -R g=u $dir; \
    done

COPY start.sh /app/start.sh