FROM quay.io/fedora/fedora:42@sha256:e337e9e2fda6293c929e0390ad99c87927b6c684453c6edb5972031917ca5d7e

LABEL org.opencontainers.image.source=https://github.com/hrrrsn/containers
LABEL org.opencontainers.image.description="Fedora image with Node.js and Git"

RUN yum -y upgrade && \
    yum -y install \
    vim nano less wget rsync nodejs npm git openssh-clients \
    && yum clean all