FROM quay.io/fedora/fedora:42@sha256:c5aa7daa0a9eda2198736cc1d6410533b0f3ee0675d2f67c166d9214af67feb0

LABEL org.opencontainers.image.source=https://github.com/hrrrsn/containers
LABEL org.opencontainers.image.description="Fedora image with Node.js and Git"

RUN yum -y upgrade && \
    yum -y install \
    vim nano less wget rsync nodejs npm git openssh-clients \
    && yum clean all