FROM quay.io/fedora/fedora:42@sha256:b23cc76519e6b2d268ba6c3532648fb848527e11e074322802b426a06170967f

LABEL org.opencontainers.image.source=https://github.com/hrrrsn/containers
LABEL org.opencontainers.image.description="Fedora image with Node.js and Git"

RUN yum -y upgrade && \
    yum -y install \
    vim nano less wget rsync nodejs npm git openssh-clients \
    && yum clean all