FROM registry.access.redhat.com/ubi10/ubi-minimal:10.2-1784669047@sha256:04140c8d78c6c6915b5c1fdad2f16d10eac3630c3339999ccdf659d8c903be50

LABEL org.opencontainers.image.source=https://github.com/hrrrsn/containers
LABEL org.opencontainers.image.description="UBI 10 minimal image with jq, rsync, and curl"

RUN microdnf install -y --setopt=install_weak_deps=0 jq rsync curl && \
    microdnf clean all
