FROM registry.access.redhat.com/ubi10/ubi-minimal:10.2-1785778687@sha256:f0ed153f25c9a3df530ccf2c49ec04430efef206083cbbc16ca76a866ef096b5

LABEL org.opencontainers.image.source=https://github.com/hrrrsn/containers
LABEL org.opencontainers.image.description="UBI 10 minimal image with jq, rsync, and curl"

RUN microdnf install -y --setopt=install_weak_deps=0 jq rsync curl && \
    microdnf clean all
