FROM registry.access.redhat.com/ubi10/ubi-minimal:10.2-1790075626@sha256:e3a5632d7ae8a97e06f634522d06187f12793e90ac0d7b51bc671c83a96d8eda

LABEL org.opencontainers.image.source=https://github.com/hrrrsn/containers
LABEL org.opencontainers.image.description="UBI 10 minimal image with jq, rsync, and curl"

RUN microdnf install -y --setopt=install_weak_deps=0 jq rsync curl && \
    microdnf clean all
