FROM registry-cdn.hpg.nz/redhat/ubi10/podman:10.2-1782294154@sha256:71b4bd5d3f7f59508a6c1402b9a5f2d4262a623dff67afa172d66a68805d8872

COPY start.sh start.sh

RUN yum install -y wget jq rsync git make nodejs procps-ng && \

    ARCH=$(uname -m) && \
    echo -e "[almalinux-crb]\nname=AlmaLinux 10 CRB\nbaseurl=https://repo.almalinux.org/almalinux/10/CRB/${ARCH}/os/\nenabled=0\ngpgcheck=0" > /etc/yum.repos.d/almalinux-crb.repo && \
    yum install -y --enablerepo=almalinux-crb lttng-ust && \
    rm -f /etc/yum.repos.d/almalinux-crb.repo && \

    curl https://api.github.com/repos/actions/runner/releases/latest | jq -r '.tag_name' | sed 's/v//' > /etc/runner-version && \
    RUNNER_VERSION=$(cat /etc/runner-version) && \
    RUNNER_ARCH=$([ "$ARCH" = "aarch64" ] && echo "arm64" || echo "x64") && \

    mkdir -p /home/podman/actions-runner && \
    cd /home/podman/actions-runner && \
    curl -O -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-${RUNNER_ARCH}-${RUNNER_VERSION}.tar.gz && \
    tar xzf ./actions-runner-linux-${RUNNER_ARCH}-${RUNNER_VERSION}.tar.gz && \
    rm -f ./actions-runner-linux-${RUNNER_ARCH}-${RUNNER_VERSION}.tar.gz && \
    /home/podman/actions-runner/bin/installdependencies.sh && \

    yum clean all -y && \
    chmod +x /start.sh && \

    for dir in /home/podman/actions-runner; do \
        chown -R podman:podman $dir; \
    done

ENTRYPOINT ["./start.sh"]