FROM registry.access.redhat.com/ubi9/podman:9.5-1746524609@sha256:17a4e3451eed24b9c9acb03489bc55cb9288f8e172b32d7d568d04e6333fa002

COPY start.sh start.sh

RUN yum upgrade -y && \
    yum install -y wget jq rsync git make nodejs procps-ng && \

    curl https://api.github.com/repos/actions/runner/releases/latest | jq -r '.tag_name' | sed 's/v//' > /etc/runner-version && \
    RUNNER_VERSION=$(cat /etc/runner-version) && \

    mkdir -p /home/podman/actions-runner && \
    cd /home/podman/actions-runner && \
    curl -O -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz && \
    tar xzf ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz && \
    rm -f ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz && \
    /home/podman/actions-runner/bin/installdependencies.sh && \

    yum clean all -y && \
    chmod +x /start.sh && \

    sed -i 's/driver = "overlay"/driver = "vfs"/g' /etc/containers/storage.conf && \

    for dir in /home/podman/actions-runner; do \
        chown -R podman:podman $dir; \
    done

ENTRYPOINT ["./start.sh"]