FROM registry.access.redhat.com/ubi9/podman:9.5-1742939433@sha256:bf3b31fa312069c211fb2bfb8f493e03dc45bb4d8673e559b65bd5f03d36628f

COPY start.sh start.sh

RUN yum upgrade -y && \
    yum install -y wget jq rsync git make nodejs procps-ng && \

    curl https://api.github.com/repos/actions/runner/releases/latest | jq -r '.tag_name' | sed 's/v//' > /etc/runner-version && \
    RUNNER_VERSION=$(cat /etc/runner-version) && \

    mkdir -p /home/podman/actions-runner && \
    cd /home/podman/actions-runner && \
    curl -O -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz && \
    tar xzf ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz && \
    rm -f ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz && \
    /home/podman/actions-runner/bin/installdependencies.sh && \

    yum clean all -y && \
    chmod +x /start.sh && \

    sed -i 's/driver = "overlay"/driver = "vfs"/g' /etc/containers/storage.conf && \

    for dir in /home/podman/actions-runner; do \
        chown -R podman:podman $dir; \
    done

ENTRYPOINT ["./start.sh"]