name: Build containers

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
  workflow_dispatch:
    inputs:
      container:
        description: 'Container directory to build'
        required: false

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Prepare and Set Matrix
        id: set-matrix
        run: |
          if [[ "${{ github.event.inputs.container }}" != "" ]]; then
            dirs="${{ github.event.inputs.container }}"
          else
            dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'docker/' | awk -F/ '{print $2}' | uniq)
          fi
          matrix_entries=()
          for dir in $dirs; do
            image_name=$(grep 'FROM' ./docker/$dir/Dockerfile | awk '{print $2}' | head -n 1)
            manifest=$(docker manifest inspect $image_name || echo "{}")
            has_arm64=$(echo "$manifest" | jq -r '.manifests[]?.platform.architecture // empty' | grep -q 'arm64' && echo 'true' || echo 'false')
            archs='["linux/amd64"]'
            if [[ $has_arm64 == "true" ]]; then
              archs='["linux/amd64", "linux/arm64"]'
            fi
            matrix_entry="{\"dir\": \"$dir\", \"platforms\": $archs}"
            matrix_entries+=("$matrix_entry")
          done
          matrix="{\"include\": [$(IFS=,; echo "${matrix_entries[*]}")]}"
          echo "Matrix: $matrix"
          echo "::set-output name=matrix::$matrix"

  build:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: ${{ fromJson(needs.prepare-matrix.outputs.matrix).include }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract base image tag from Dockerfile
        id: extract-info
        run: |
          base_image=$(grep FROM docker/${{ matrix.container.dir }}/Dockerfile | awk '{print $2}' | head -n 1)
          base_image_tag=$(echo "$base_image" | awk -F':' '{print $2}' | awk -F'@' '{print $1}')
          if [ -z "$base_image_tag" ]; then
            base_image_tag="latest"
          fi
          echo "BASE_IMAGE_TAG=$base_image_tag" >> $GITHUB_ENV
          echo "BASE_IMAGE_TAG: $base_image_tag"
          commit_hash=$(git rev-parse HEAD | cut -c 1-8)
          echo "COMMIT_HASH=$commit_hash" >> $GITHUB_ENV
          echo "COMMIT_HASH: $commit_hash"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./docker/${{ matrix.container.dir }}
          push: true
          platforms: ${{ join(matrix.container.platforms, ',') }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.container.dir }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.container.dir }}:${{ env.COMMIT_HASH }}
            ghcr.io/${{ github.repository }}/${{ matrix.container.dir }}:${{ env.BASE_IMAGE_TAG }}
            ghcr.io/${{ github.repository }}/${{ matrix.container.dir }}:${{ env.BASE_IMAGE_TAG }}-${{ env.COMMIT_HASH }}
            ghcr.io/${{ github.repository }}/${{ matrix.container.dir }}:${{ env.BASE_IMAGE_TAG }}-${{ github.run_number }}